name: Update documentation

on:
  repository_dispatch:
    types: [update_docs]

jobs:
  update_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Checkout bepro-js@master
        uses: actions/checkout@v2
        with:
          repository: bepronetwork/bepro-js
          path: bepro-src
          ref: master

      - name: npm ci
        run: npm ci

      - name: vue:build
        run: npm run build

      - name: jsdoc:build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./bepro-src/src
          output_dir: ./dist/static/docs.json
          recurse: true
          template: jsdoc-json

      - name: copy readme.md
        run: cp bepro-src/README.md dist/static/readme.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist

